version: '3'
services:
  database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=Admin1234_
  dbfrontend:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - 8877:80
    environment:
      - PMA_HOST=database
